#!/usr/bin/env bash
set -Eeuo pipefail

sudo install -d -m 0755 /run/sshd
sudo ssh-keygen -A
sudo /usr/sbin/sshd -t
if ! pgrep -x sshd >/dev/null; then
  sudo /usr/sbin/sshd
fi

if (($# == 0)); then
  set -- sleep infinity
fi
exec "$@"
